package com.macro.mall.mapper;

import com.macro.mall.model.PtnServicePoint;
import com.macro.mall.model.PtnServicePointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtnServicePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    long countByExample(PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int deleteByExample(PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int insert(PtnServicePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int insertSelective(PtnServicePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    List<PtnServicePoint> selectByExample(PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    PtnServicePoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByExampleSelective(@Param("record") PtnServicePoint record, @Param("example") PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByExample(@Param("record") PtnServicePoint record, @Param("example") PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByPrimaryKeySelective(PtnServicePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByPrimaryKey(PtnServicePoint record);
}