package com.macro.mall.mapper;

import com.macro.mall.model.PtnServicePoint;
import com.macro.mall.model.PtnServicePointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtnServicePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    long countByExample(PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int deleteByExample(PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int insert(PtnServicePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int insertSelective(PtnServicePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    List<PtnServicePoint> selectByExample(PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    PtnServicePoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByExampleSelective(@Param("record") PtnServicePoint record,
            @Param("example") PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByExample(@Param("record") PtnServicePoint record, @Param("example") PtnServicePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByPrimaryKeySelective(PtnServicePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    int updateByPrimaryKey(PtnServicePoint record);

    /**
     * 根据网点类型查询
     */
    List<PtnServicePoint> selectByType(Integer type);

    /**
     * 更新网点状态
     */
    int updateStatus(@Param("id") Long id, @Param("status") Integer status);

    /**
     * 更新业务数量
     */
    int updateBillCount(@Param("id") Long id, @Param("selfPickCount") Integer selfPickCount,
            @Param("receiveCount") Integer receiveCount);

    /**
     * 更新服务星级
     */
    int updateServiceRating(@Param("id") Long id, @Param("rating") Integer rating);
}