package com.macro.mall.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OmsAfterSale implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Long id;

    @ApiModelProperty(value = "订单id")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.order_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Long orderId;

    @ApiModelProperty(value = "订单编号")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.order_sn
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String orderSn;

    @ApiModelProperty(value = "用户id")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.member_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Long memberId;

    @ApiModelProperty(value = "用户名")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.member_username
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String memberUsername;

    @ApiModelProperty(value = "退款金额")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.return_amount
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private BigDecimal returnAmount;

    @ApiModelProperty(value = "售后类型：0->退款；1->退货退款")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.type
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Integer type;

    @ApiModelProperty(value = "申请状态：0->待处理；1->处理中；2->已完成；3->已拒绝")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.status
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Integer status;

    @ApiModelProperty(value = "申请时间")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.create_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.update_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Date updateTime;

    @ApiModelProperty(value = "处理时间")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.handle_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Date handleTime;

    @ApiModelProperty(value = "处理人")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.handle_man
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String handleMan;

    @ApiModelProperty(value = "处理备注")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.handle_note
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String handleNote;

    @ApiModelProperty(value = "退货地址id (关联公司收货地址表)")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale.company_address_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Long companyAddressId;

    @ApiModelProperty(value = "退货人姓名")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.return_name
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String returnName;

    @ApiModelProperty(value = "退货人电话")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.return_phone
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String returnPhone;

    @ApiModelProperty(value = "原因")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.reason
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String reason;

    @ApiModelProperty(value = "描述")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.description
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String description;

    @ApiModelProperty(value = "凭证图片，以逗号隔开")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.proof_pics
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String proofPics;

    @ApiModelProperty(value = "收货人")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.receive_man
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String receiveMan;

    @ApiModelProperty(value = "收货时间")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.receive_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private Date receiveTime;

    @ApiModelProperty(value = "收货备注")
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.receive_note
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private String receiveNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_after_sale
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.id
     *
     * @return the value of oms_after_sale.id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.id
     *
     * @param id the value for oms_after_sale.id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.order_id
     *
     * @return the value of oms_after_sale.order_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.order_id
     *
     * @param orderId the value for oms_after_sale.order_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.order_sn
     *
     * @return the value of oms_after_sale.order_sn
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.order_sn
     *
     * @param orderSn the value for oms_after_sale.order_sn
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.member_id
     *
     * @return the value of oms_after_sale.member_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.member_id
     *
     * @param memberId the value for oms_after_sale.member_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.member_username
     *
     * @return the value of oms_after_sale.member_username
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getMemberUsername() {
        return memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale.member_username
     *
     * @param memberUsername the value for oms_after_sale.member_username
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setMemberUsername(String memberUsername) {
        this.memberUsername = memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.return_amount
     *
     * @return the value of oms_after_sale.return_amount
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public BigDecimal getReturnAmount() {
        return returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale.return_amount
     *
     * @param returnAmount the value for oms_after_sale.return_amount
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReturnAmount(BigDecimal returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.type
     *
     * @return the value of oms_after_sale.type
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.type
     *
     * @param type the value for oms_after_sale.type
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.status
     *
     * @return the value of oms_after_sale.status
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.status
     *
     * @param status the value for oms_after_sale.status
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.create_time
     *
     * @return the value of oms_after_sale.create_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.create_time
     *
     * @param createTime the value for oms_after_sale.create_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.update_time
     *
     * @return the value of oms_after_sale.update_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.update_time
     *
     * @param updateTime the value for oms_after_sale.update_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.handle_time
     *
     * @return the value of oms_after_sale.handle_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.handle_time
     *
     * @param handleTime the value for oms_after_sale.handle_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.handle_man
     *
     * @return the value of oms_after_sale.handle_man
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getHandleMan() {
        return handleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.handle_man
     *
     * @param handleMan the value for oms_after_sale.handle_man
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setHandleMan(String handleMan) {
        this.handleMan = handleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.handle_note
     *
     * @return the value of oms_after_sale.handle_note
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getHandleNote() {
        return handleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.handle_note
     *
     * @param handleNote the value for oms_after_sale.handle_note
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setHandleNote(String handleNote) {
        this.handleNote = handleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.company_address_id
     *
     * @return the value of oms_after_sale.company_address_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getCompanyAddressId() {
        return companyAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale.company_address_id
     *
     * @param companyAddressId the value for oms_after_sale.company_address_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setCompanyAddressId(Long companyAddressId) {
        this.companyAddressId = companyAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.return_name
     *
     * @return the value of oms_after_sale.return_name
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getReturnName() {
        return returnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.return_name
     *
     * @param returnName the value for oms_after_sale.return_name
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReturnName(String returnName) {
        this.returnName = returnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.return_phone
     *
     * @return the value of oms_after_sale.return_phone
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getReturnPhone() {
        return returnPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.return_phone
     *
     * @param returnPhone the value for oms_after_sale.return_phone
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReturnPhone(String returnPhone) {
        this.returnPhone = returnPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.reason
     *
     * @return the value of oms_after_sale.reason
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.reason
     *
     * @param reason the value for oms_after_sale.reason
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.description
     *
     * @return the value of oms_after_sale.description
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.description
     *
     * @param description the value for oms_after_sale.description
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.proof_pics
     *
     * @return the value of oms_after_sale.proof_pics
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getProofPics() {
        return proofPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.proof_pics
     *
     * @param proofPics the value for oms_after_sale.proof_pics
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProofPics(String proofPics) {
        this.proofPics = proofPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.receive_man
     *
     * @return the value of oms_after_sale.receive_man
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getReceiveMan() {
        return receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.receive_man
     *
     * @param receiveMan the value for oms_after_sale.receive_man
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReceiveMan(String receiveMan) {
        this.receiveMan = receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.receive_time
     *
     * @return the value of oms_after_sale.receive_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.receive_time
     *
     * @param receiveTime the value for oms_after_sale.receive_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale.receive_note
     *
     * @return the value of oms_after_sale.receive_note
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getReceiveNote() {
        return receiveNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.receive_note
     *
     * @param receiveNote the value for oms_after_sale.receive_note
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReceiveNote(String receiveNote) {
        this.receiveNote = receiveNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_after_sale
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", memberId=").append(memberId);
        sb.append(", memberUsername=").append(memberUsername);
        sb.append(", returnAmount=").append(returnAmount);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", handleTime=").append(handleTime);
        sb.append(", handleMan=").append(handleMan);
        sb.append(", handleNote=").append(handleNote);
        sb.append(", companyAddressId=").append(companyAddressId);
        sb.append(", returnName=").append(returnName);
        sb.append(", returnPhone=").append(returnPhone);
        sb.append(", reason=").append(reason);
        sb.append(", description=").append(description);
        sb.append(", proofPics=").append(proofPics);
        sb.append(", receiveMan=").append(receiveMan);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", receiveNote=").append(receiveNote);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}