package com.macro.mall.model;

import java.io.Serializable;
import java.util.Date;

public class OmsAfterSale implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.order_id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.member_id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.status
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.handle_note
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private String handleNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.handle_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private Date handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.create_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale.update_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_after_sale
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.id
     *
     * @return the value of oms_after_sale.id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.id
     *
     * @param id the value for oms_after_sale.id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.order_id
     *
     * @return the value of oms_after_sale.order_id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.order_id
     *
     * @param orderId the value for oms_after_sale.order_id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.member_id
     *
     * @return the value of oms_after_sale.member_id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.member_id
     *
     * @param memberId the value for oms_after_sale.member_id
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.status
     *
     * @return the value of oms_after_sale.status
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.status
     *
     * @param status the value for oms_after_sale.status
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.handle_note
     *
     * @return the value of oms_after_sale.handle_note
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public String getHandleNote() {
        return handleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.handle_note
     *
     * @param handleNote the value for oms_after_sale.handle_note
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setHandleNote(String handleNote) {
        this.handleNote = handleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.handle_time
     *
     * @return the value of oms_after_sale.handle_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.handle_time
     *
     * @param handleTime the value for oms_after_sale.handle_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.create_time
     *
     * @return the value of oms_after_sale.create_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.create_time
     *
     * @param createTime the value for oms_after_sale.create_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale.update_time
     *
     * @return the value of oms_after_sale.update_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale.update_time
     *
     * @param updateTime the value for oms_after_sale.update_time
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_after_sale
     *
     * @mbg.generated Sun Apr 13 18:28:46 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", memberId=").append(memberId);
        sb.append(", status=").append(status);
        sb.append(", handleNote=").append(handleNote);
        sb.append(", handleTime=").append(handleTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}