package com.macro.mall.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OmsAfterSaleItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale_item.id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "主键ID")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.after_sale_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "售后单ID")
    private Long afterSaleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.order_item_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "订单商品项ID")
    private Long orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale_item.product_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "商品ID")
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.product_name
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "商品名称")
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale_item.product_pic
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "商品图片")
    private String productPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.product_brand
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "商品品牌")
    private String productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.product_price
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "商品价格")
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.product_real_price
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "实际支付价格")
    private BigDecimal productRealPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.product_attr
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "商品属性，格式为json")
    private String productAttr;

    /**
     * 商品sku ID
     */
    @ApiModelProperty(value = "商品sku ID")
    private Long productSkuId;

    /**
     * 商品sku编码
     */
    @ApiModelProperty(value = "商品sku编码")
    private String productSkuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.product_quantity
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "购买数量")
    private Integer productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.return_quantity
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "退货数量")
    private Integer returnQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * oms_after_sale_item.return_reason
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "退货原因")
    private String returnReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale_item.create_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "创建时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale_item.update_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "更新时间")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale_item.del_flag
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "删除标记：0->未删除；1->已删除")
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_after_sale_item.version
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @ApiModelProperty(value = "版本号")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_after_sale_item
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_after_sale_item.id
     *
     * @return the value of oms_after_sale_item.id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale_item.id
     *
     * @param id the value for oms_after_sale_item.id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.after_sale_id
     *
     * @return the value of oms_after_sale_item.after_sale_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getAfterSaleId() {
        return afterSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.after_sale_id
     *
     * @param afterSaleId the value for oms_after_sale_item.after_sale_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setAfterSaleId(Long afterSaleId) {
        this.afterSaleId = afterSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.order_item_id
     *
     * @return the value of oms_after_sale_item.order_item_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.order_item_id
     *
     * @param orderItemId the value for oms_after_sale_item.order_item_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_id
     *
     * @return the value of oms_after_sale_item.product_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_id
     *
     * @param productId the value for oms_after_sale_item.product_id
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_name
     *
     * @return the value of oms_after_sale_item.product_name
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_name
     *
     * @param productName the value for oms_after_sale_item.product_name
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_pic
     *
     * @return the value of oms_after_sale_item.product_pic
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_pic
     *
     * @param productPic the value for oms_after_sale_item.product_pic
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_brand
     *
     * @return the value of oms_after_sale_item.product_brand
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_brand
     *
     * @param productBrand the value for oms_after_sale_item.product_brand
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_price
     *
     * @return the value of oms_after_sale_item.product_price
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_price
     *
     * @param productPrice the value for oms_after_sale_item.product_price
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_real_price
     *
     * @return the value of oms_after_sale_item.product_real_price
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public BigDecimal getProductRealPrice() {
        return productRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_real_price
     *
     * @param productRealPrice the value for oms_after_sale_item.product_real_price
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductRealPrice(BigDecimal productRealPrice) {
        this.productRealPrice = productRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_attr
     *
     * @return the value of oms_after_sale_item.product_attr
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getProductAttr() {
        return productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_attr
     *
     * @param productAttr the value for oms_after_sale_item.product_attr
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductAttr(String productAttr) {
        this.productAttr = productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.product_quantity
     *
     * @return the value of oms_after_sale_item.product_quantity
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Integer getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.product_quantity
     *
     * @param productQuantity the value for oms_after_sale_item.product_quantity
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.return_quantity
     *
     * @return the value of oms_after_sale_item.return_quantity
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Integer getReturnQuantity() {
        return returnQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.return_quantity
     *
     * @param returnQuantity the value for oms_after_sale_item.return_quantity
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReturnQuantity(Integer returnQuantity) {
        this.returnQuantity = returnQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.return_reason
     *
     * @return the value of oms_after_sale_item.return_reason
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public String getReturnReason() {
        return returnReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.return_reason
     *
     * @param returnReason the value for oms_after_sale_item.return_reason
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setReturnReason(String returnReason) {
        this.returnReason = returnReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.create_time
     *
     * @return the value of oms_after_sale_item.create_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.create_time
     *
     * @param createTime the value for oms_after_sale_item.create_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.update_time
     *
     * @return the value of oms_after_sale_item.update_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.update_time
     *
     * @param updateTime the value for oms_after_sale_item.update_time
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.del_flag
     *
     * @return the value of oms_after_sale_item.del_flag
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * oms_after_sale_item.del_flag
     *
     * @param delFlag the value for oms_after_sale_item.del_flag
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * oms_after_sale_item.version
     *
     * @return the value of oms_after_sale_item.version
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_after_sale_item.version
     *
     * @param version the value for oms_after_sale_item.version
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * 获取商品sku ID
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * 设置商品sku ID
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * 获取商品sku编码
     */
    public String getProductSkuCode() {
        return productSkuCode;
    }

    /**
     * 设置商品sku编码
     */
    public void setProductSkuCode(String productSkuCode) {
        this.productSkuCode = productSkuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_after_sale_item
     *
     * @mbg.generated Mon Apr 14 10:16:04 CST 2025
     */
    @Override
    public String toString() {
        return "OmsAfterSaleItem{" +
                "id=" + id +
                ", afterSaleId=" + afterSaleId +
                ", orderItemId=" + orderItemId +
                ", productId=" + productId +
                ", productName='" + productName + '\'' +
                ", productPic='" + productPic + '\'' +
                ", productBrand='" + productBrand + '\'' +
                ", productPrice=" + productPrice +
                ", productRealPrice=" + productRealPrice +
                ", productAttr='" + productAttr + '\'' +
                ", productQuantity=" + productQuantity +
                ", returnQuantity=" + returnQuantity +
                ", returnReason='" + returnReason + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", delFlag=" + delFlag +
                ", version=" + version +
                ", productSkuId=" + productSkuId +
                ", productSkuCode='" + productSkuCode + '\'' +
                '}';
    }
}