package com.macro.mall.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PtnServicePoint implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.id
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.location_name
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.location_address
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private String locationAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.location_longitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private BigDecimal locationLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.location_latitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private BigDecimal locationLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.create_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.update_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.id
     *
     * @return the value of ptn_service_point.id
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.id
     *
     * @param id the value for ptn_service_point.id
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.location_name
     *
     * @return the value of ptn_service_point.location_name
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.location_name
     *
     * @param locationName the value for ptn_service_point.location_name
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.location_address
     *
     * @return the value of ptn_service_point.location_address
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public String getLocationAddress() {
        return locationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.location_address
     *
     * @param locationAddress the value for ptn_service_point.location_address
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationAddress(String locationAddress) {
        this.locationAddress = locationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.location_longitude
     *
     * @return the value of ptn_service_point.location_longitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public BigDecimal getLocationLongitude() {
        return locationLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.location_longitude
     *
     * @param locationLongitude the value for ptn_service_point.location_longitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationLongitude(BigDecimal locationLongitude) {
        this.locationLongitude = locationLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.location_latitude
     *
     * @return the value of ptn_service_point.location_latitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public BigDecimal getLocationLatitude() {
        return locationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.location_latitude
     *
     * @param locationLatitude the value for ptn_service_point.location_latitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationLatitude(BigDecimal locationLatitude) {
        this.locationLatitude = locationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.create_time
     *
     * @return the value of ptn_service_point.create_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.create_time
     *
     * @param createTime the value for ptn_service_point.create_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.update_time
     *
     * @return the value of ptn_service_point.update_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.update_time
     *
     * @param updateTime the value for ptn_service_point.update_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", locationName=").append(locationName);
        sb.append(", locationAddress=").append(locationAddress);
        sb.append(", locationLongitude=").append(locationLongitude);
        sb.append(", locationLatitude=").append(locationLatitude);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}