package com.macro.mall.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PtnServicePoint implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.id
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.location_name
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * ptn_service_point.location_address
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private String locationAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * ptn_service_point.location_longitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private BigDecimal locationLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column
     * ptn_service_point.location_latitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private BigDecimal locationLatitude;

    /**
     * 服务点状态：0->正常；1->已关闭
     */
    @ApiModelProperty(value = "服务点状态：0->正常；1->已关闭")
    private Integer servicePointStatus;

    /**
     * 服务点类型：0->自提点; 1->收货点; 2->综合点
     */
    @ApiModelProperty(value = "服务点类型：0->自提点; 1->收货点; 2->综合点")
    private Integer servicePointType;

    /**
     * 服务点负责人
     */
    @ApiModelProperty(value = "服务点负责人")
    private String contactName;

    /**
     * 负责人电话
     */
    @ApiModelProperty(value = "负责人电话")
    private String contactPhone;

    /**
     * 服务点备注
     */
    @ApiModelProperty(value = "服务点备注")
    private String servicePointRemark;

    /**
     * 服务点图片
     */
    @ApiModelProperty(value = "服务点图片")
    private String servicePointPic;

    /**
     * 服务时间类型：0->全天; 1->指定时间
     */
    @ApiModelProperty(value = "服务时间类型：0->全天; 1->指定时间")
    private Integer serviceTimeType;

    /**
     * 服务时间列表
     */
    @ApiModelProperty(value = "服务时间列表")
    private String serviceTimeList;

    /**
     * 服务星级：0->1星; 1->2星; 2->3星; 3->4星; 4->5星
     */
    @ApiModelProperty(value = "服务星级：0->1星; 1->2星; 2->3星; 3->4星; 4->5星")
    private Integer serviceStarRating;

    /**
     * 自提单量
     */
    @ApiModelProperty(value = "自提单量")
    private Integer selfPickBillCount;

    /**
     * 收货单量
     */
    @ApiModelProperty(value = "收货单量")
    private Integer receiveBillCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.create_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptn_service_point.update_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptn_service_point.id
     *
     * @return the value of ptn_service_point.id
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptn_service_point.id
     *
     * @param id the value for ptn_service_point.id
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * ptn_service_point.location_name
     *
     * @return the value of ptn_service_point.location_name
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * ptn_service_point.location_name
     *
     * @param locationName the value for ptn_service_point.location_name
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * ptn_service_point.location_address
     *
     * @return the value of ptn_service_point.location_address
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public String getLocationAddress() {
        return locationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * ptn_service_point.location_address
     *
     * @param locationAddress the value for ptn_service_point.location_address
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationAddress(String locationAddress) {
        this.locationAddress = locationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * ptn_service_point.location_longitude
     *
     * @return the value of ptn_service_point.location_longitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public BigDecimal getLocationLongitude() {
        return locationLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * ptn_service_point.location_longitude
     *
     * @param locationLongitude the value for ptn_service_point.location_longitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationLongitude(BigDecimal locationLongitude) {
        this.locationLongitude = locationLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * ptn_service_point.location_latitude
     *
     * @return the value of ptn_service_point.location_latitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public BigDecimal getLocationLatitude() {
        return locationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * ptn_service_point.location_latitude
     *
     * @param locationLatitude the value for ptn_service_point.location_latitude
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setLocationLatitude(BigDecimal locationLatitude) {
        this.locationLatitude = locationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * ptn_service_point.create_time
     *
     * @return the value of ptn_service_point.create_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * ptn_service_point.create_time
     *
     * @param createTime the value for ptn_service_point.create_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * ptn_service_point.update_time
     *
     * @return the value of ptn_service_point.update_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column
     * ptn_service_point.update_time
     *
     * @param updateTime the value for ptn_service_point.update_time
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getServicePointStatus() {
        return servicePointStatus;
    }

    public void setServicePointStatus(Integer servicePointStatus) {
        this.servicePointStatus = servicePointStatus;
    }

    public Integer getServicePointType() {
        return servicePointType;
    }

    public void setServicePointType(Integer servicePointType) {
        this.servicePointType = servicePointType;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getServicePointRemark() {
        return servicePointRemark;
    }

    public void setServicePointRemark(String servicePointRemark) {
        this.servicePointRemark = servicePointRemark;
    }

    public String getServicePointPic() {
        return servicePointPic;
    }

    public void setServicePointPic(String servicePointPic) {
        this.servicePointPic = servicePointPic;
    }

    public Integer getServiceTimeType() {
        return serviceTimeType;
    }

    public void setServiceTimeType(Integer serviceTimeType) {
        this.serviceTimeType = serviceTimeType;
    }

    public String getServiceTimeList() {
        return serviceTimeList;
    }

    public void setServiceTimeList(String serviceTimeList) {
        this.serviceTimeList = serviceTimeList;
    }

    public Integer getServiceStarRating() {
        return serviceStarRating;
    }

    public void setServiceStarRating(Integer serviceStarRating) {
        this.serviceStarRating = serviceStarRating;
    }

    public Integer getSelfPickBillCount() {
        return selfPickBillCount;
    }

    public void setSelfPickBillCount(Integer selfPickBillCount) {
        this.selfPickBillCount = selfPickBillCount;
    }

    public Integer getReceiveBillCount() {
        return receiveBillCount;
    }

    public void setReceiveBillCount(Integer receiveBillCount) {
        this.receiveBillCount = receiveBillCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptn_service_point
     *
     * @mbg.generated Mon Apr 21 13:21:25 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", locationName=").append(locationName);
        sb.append(", locationAddress=").append(locationAddress);
        sb.append(", locationLongitude=").append(locationLongitude);
        sb.append(", locationLatitude=").append(locationLatitude);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}